### ISSUE TITLE
Weird error message - Argument X

### ISSUE THREAD

**Issue by nedzadarek** [vasil-sd/shen-libs#19]
If we type wrong type of argument, we are going to get weird message. For example:
```Shen
(define mul
A B -> (* A B)
)
(mul 2 "F") \* Argument X is not a NUMBER: "F" *\
(mul  "F" 2) \* Argument X is not a NUMBER: "F" *\
(mul  "F" "F") \* Argument X is not a NUMBER: "F" *\
```
I don't have any X. 
Macros display the same message.

It should display something like: 
`Argument A is not a NUMBER: "F"` 
``` 
Wrong type(s):
A - not a NUMBER
B - not a NUMBER
```

**Comment by gravicappa** [comment]
What Shen implementation are you running? I've checked Shen-sbcl and Shen-clisp, both have different error messages.
Shen-SBCL:
 ~~~
(3-) (mul 2 "F")
The value "F" is not of type REAL.
~~~

Shen-Clisp:
~~~
(5-) (mul 2 "F")
COERCE: "F" is not a real number
~~~

**Comment by nedzadarek** [comment]
Shen, copyright (C) 2010-2015 Mark Tarver
www.shenlanguage.org, Shen 19.2
running under Common Lisp, implementation: SBCL
port 2.0 ported by Mark Tarver
on Windows

**Comment by gravicappa** [comment]
Can you show the result of `(lisp.lisp-implementation-version)`?
I have a suspicion that it is an error message from SBCL itself since Shen sources does not contain such string.

**Comment by nedzadarek** [comment]
```
(18-) (lisp.lisp-implementation-version)  
"1.1.1"
```

**Comment by gravicappa** [comment]
I checked: that message belongs to SBCL itself so Shen cannot control its contents.
Thanks for reporting though (to the wrong repo, but nevermind).
