### ISSUE TITLE
modulesys load-fn is 0 place, and (function F) doesn't work in such cases.

### ISSUE THREAD

**Issue by tizoc** [vasil-sd/shen-libs#23]
Since Shen doesn't register a lambda form for 0-place functions this breaks in `load-module-sources`

One possible solution is to make it so that `load-fn` is a 1-place function, another one is to use `freeze`/`thaw` instead of a symbol.

I think like the first option better (keeps the spec definition the same).

**Comment by tizoc** [comment]
For the first solution the change would look like this, and modules that use a custom `load-fn`(like "maths") have to be updated by adding an extra argument to the function.

```diff
diff --git a/modulesys.shen b/modulesys.shen
index 163373c..e1d000a 100644
--- a/modulesys.shen
+++ b/modulesys.shen
@@ -193,7 +193,7 @@
   M -> (let F (get M load-fn (value *db*))
             R (if (= F (value *nil-load*))
                   (load-module-files (get M load (value *db*)))
-                  ((function F)))
+                  ((function F) load))
             . (set *list* [M | (value *list*)])
          R))
```

**Comment by tizoc** [comment]
For maths:

```diff
diff --git a/maths/module.shen b/maths/module.shen
index 4703d02..6a895be 100644
--- a/maths/module.shen
+++ b/maths/module.shen
@@ -9,7 +9,8 @@
   _ _ -> true)
 
 (define maths-load
-  {--> boolean}
-  -> (do (load/tc - "macro-def.shen")
+  {X --> boolean}
+  _ -> (do
+         (load/tc - "macro-def.shen")
          (load "maths-lib.shen")
          (maths-load-native (language) (implementation))))
```

**Comment by tizoc** [comment]
3rd option is to make the load-fn parameter a lambda instead of a symbol, but like the freeze option, this means that the signature changes. Not sure if it is a big deal because as far as I know all the code that uses modulesys is in this repository, which means it is easy to update every module in a single pass.

I can submit a pull request to have everything updated, I just have to know which solution we agree on.

**Comment by gravicappa** [comment]
`load-fn`, `unload-fn` and `translate-fn` are symbols in order to allow `register-module` call be placed at the top of `module.shen` above the definitions of that functions, so it's kind of a header. I think that it's save to settle on 1-arity functions for `load-fn` and `unload-fn`.

**Comment by tizoc** [comment]
Ok, great. Will submit a PR, I was just checking and it is only a few modules that require updating.

**Comment by gravicappa** [comment]
Not many modules employ that mechanism as far as I remember.
